# -*- coding: utf-8 -*-
"""PRI2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Ocui9ix2zSGoa6QY6JyKxmyTYJ-XuUa
"""

T = int(input())
numbers = []
for i in range(T):
  string = input()
  numbers.append([])
  for character in string:
    numbers[i].append(character)
for number in numbers:
  result = number[:]
  repititions = 0
  while True:
    if result == ['1']:
      break
    repititions += 1
    if result[len(result)-1] == '0':
      del result[len(result)-1]
    else:
      i = len(result) - 1
      while i >= 0:
        if result[i] == '0':
          result[i] = '1'
          break
        else:
          result[i] = '0'
          if i == 0:
            result.insert(0, '1')
            break
        i -= 1
  print(repititions)