# -*- coding: utf-8 -*-
"""PRB2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12tt7GaQgnBCO0kGLRZ8WWGPq3SqToEe8
"""

vowels = ["a", "e", "i", "o", "u"]
T = int(input())
haikus = []
for i in range(T):
  haikus.append([])
  for n in range(3):
    haikus[i].append(input())
for haiku in haikus:
  vowelcount = 0
  for letter in haiku[0]:
    if letter in vowels:
      vowelcount += 1
  if vowelcount != 5:
    print("NO")
    continue
  vowelcount = 0
  for letter in haiku[1]:
    if letter in vowels:
      vowelcount += 1
  if vowelcount != 7:
    print("NO")
    continue
  vowelcount = 0
  for letter in haiku[2]:
    if letter in vowels:
      vowelcount += 1
  if vowelcount != 5:
    print("NO")
    continue
  print("YES")