# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12BU-mX91e0_90FJ6oS4uVw2VaPncxt8S
"""

n = input()
print(int(n) + 1)