# -*- coding: utf-8 -*-
"""PRA1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12BU-mX91e0_90FJ6oS4uVw2VaPncxt8S
"""

T = int(input())
cases = []
for i in range(T):
  cases.append(int(input()))
for i in range(T):
  addition = 0
  while True:
    GCD = 1
    number = cases[i] + addition
    addition += 1
    sumdigits = 0
    for l in range(len(str(number))):
      sumdigits += int(str(number)[l])
    for n in range(2, sumdigits + 1):
      if sumdigits % n == 0 and number % n == 0:
        GCD = n
    if GCD != 1:
      print(number)
      break